<div>
    <img src="/uploads/image/hot/icon.png" alt="Hot" width="140" height="140" class="pull-right" />
</div>
<p>
    <strong>Hot is macOS menu bar application that displays the CPU speed limit due to thermal issues.</strong>
</p>
<blockquote>
CPU throttling is a power management technique in computer architecture whereby the frequency of a microprocessor can be automatically adjusted "on the fly" depending on the actual needs, to conserve power and reduce the amount of heat generated by the chip<br />
Source: <a href="https://en.wikipedia.org/wiki/Dynamic_frequency_scaling" title="Dynamic frequency scaling">Wikipedia</a>
</blockquote>
<h3 class="clearer">Download &amp; Source Code</h3>
<ul>
    <li>Latest release: <a href="https://github.com/macmade/Hot/releases/latest" title="Latest release">github.com/macmade/Hot/releases/latest</a></li>
    <li>Source code: <a href="https://github.com/macmade/Hot" title="Source code">github.com/macmade/Hot</a></li>
</ul>
<h3 class="clearer">Screenshots</h3>
<div class="row">
    <div class="col-xs-4">
        <a href="/uploads/image/hot/screenshot-full.png" class="lightbox"><img src="/uploads/image/hot/screenshot.png" alt="" width="200" height="307" class="img-thumbnail" /></a>
    </div>
</div>
